# Generated by Django 5.2.6 on 2025-09-23 21:01

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ChineseWord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hanzi', models.CharField(max_length=50, verbose_name='Иероглифы')),
                ('pinyin', models.CharField(max_length=100, verbose_name='Пиньинь')),
                ('translation', models.CharField(max_length=200, verbose_name='Перевод на русский')),
                ('category', models.CharField(blank=True, choices=[('существительное', 'Существительное'), ('глагол', 'Глагол'), ('прилагательное', 'Прилагательное'), ('наречие', 'Наречие'), ('другое', 'Другое')], max_length=50, verbose_name='Категория')),
                ('example', models.TextField(blank=True, verbose_name='Пример использования')),
                ('date_added', models.DateTimeField(auto_now_add=True, verbose_name='Дата добавления')),
            ],
            options={
                'verbose_name': 'Китайское слово',
                'verbose_name_plural': 'Китайские слова',
            },
        ),
    ]
