# Generated by Django 5.2.6 on 2025-09-29 06:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('flashcards', '0002_chineseword_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='chineseword',
            name='difficulty',
            field=models.IntegerField(choices=[(0, 'Новое'), (1, 'Легкое'), (2, 'Среднее'), (3, 'Сложное')], default=0, verbose_name='Сложность'),
        ),
    ]
